# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24b54c697da07bd19b1f7f4e65c5437e71fb23630a7ce49764e6b09de94f3030dbcdbfa01660bc4844c4b56adb81ac6fb720883426bea2b3dfd1d46938bf25e7

test:
  secret_key_base: 6549c22af567691d7dfe3354c84bfc4a3f81206da3b7b18f9bf0509c0910d2f3e1f852cf1e32a323eed91a77102faadc6a3236baa3c960a1bbabc9ce5da68226

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
